### PR TITLE
Use certain best practices

### PR DESCRIPTION
**Pull request by davebaol**
- static final loggers 
- final class with private constructor
- EnumMap

### CODE REVIEW

**Comment by Turbo87** [comment]
@davebaol there are quite a lot of unrelated whitespace changes in that commit which makes it really hard to review that

**Comment by davebaol** [comment]
Yeah, not sure why. Maybe something due to line ending or so.
Anyways if you add `?w=1` to the url the actual changes become evident.

**Comment by mgodave** [comment]
sorry, someone care to merge master and update the pr. I'll merge it.

**Comment by Turbo87** [comment]
I'm still not happy about the unnecessary whitespace changes tbh

**Comment by davebaol** [comment]
You're not happy with line endings and I won't resolve conflicts soon. So let's close this.

**Pull request closed without merging**
