### PR TITLE
Add TravisCI support

### PR DESCRIPTION
**Pull request by Turbo87**
This enables us to use the [TravisCI](https://travis-ci.org) integration server. 

@mgodave I have activated it for my forked repo, but you should probably activate it for this repo to. Have a look at http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in for instructions.

### CODE REVIEW

**Comment by Turbo87** [comment]
Example: https://travis-ci.org/Turbo87/esl-client/builds/60782399

**Comment by Turbo87** [comment]
@mgodave have you activated TravisCI for this repo yet?

**Comment by mgodave** [comment]
No, sorry, I forgot.

**Comment by mgodave** [comment]
OK, just enabled travis and triggered a build

**Pull request merged**
